apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-service.name" . }}
  labels:
    {{- include "kubernetes-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kubernetes-service.name" . }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        app: {{ include "kubernetes-service.name" . }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if kindIs "map" .Values.env }}
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- else }}
            {{- range $index, $val := .Values.env }}
            - name: {{ $val.name }}
              {{- if $val.value }}
              value: {{ $val.value | quote }}
              {{- else }}
              valueFrom:
              {{- toYaml $val.valueFrom | nindent 16 -}}
              {{- end }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
      {{- if and (eq .Values.appType "django") .Values.runMigrations }}
      initContainers:
        - name: {{ .Chart.Name }}-app-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            {{- if kindIs "map" .Values.env }}
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- else }}
            {{- range $index, $val := .Values.env }}
            - name: {{ $val.name }}
              {{- if $val.value }}
              value: {{ $val.value | quote }}
              {{- else }}
              valueFrom:
              {{- toYaml $val.valueFrom | nindent 16 -}}
              {{- end }}
            {{- end }}
            {{- end }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - python manage.py migrate
        {{ end }}