apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-service.name" . }}
  labels:
    {{- include "kubernetes-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kubernetes-service.name" . }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        app: {{ include "kubernetes-service.name" . }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{ range .Values.env }}
            - name: {{ .name | quote | nindent 12 }}
              value: {{ .value | quote| nindent 14 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}