apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-service.name" . }}
  labels:
    {{- include "kubernetes-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    app: {{ include "kubernetes-service.name" . }}